Ziyara/src/Entity/Pack.php
<?php

namespace App\Entity;

use App\Repository\PackRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PackRepository::class)]
class Pack
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 255)]
    private ?string $titre_Pack = null;

    #[ORM\Column(length: 255)]
    private ?string $description_Pack = null;

    #[ORM\Column(length: 255)]
    private ?string $prix_Pack = null;

    #[ORM\Column(length: 255)]
    private ?string $date_Pack = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdPack(): ?string
    {
        return $this->id_Pack;
    }

    public function setIdPack(string $id_Pack): static
    {
        $this->id_Pack = $id_Pack;

        return $this;
    }

    public function getTitrePack(): ?string
    {
        return $this->titre_Pack;
    }

    public function setTitrePack(string $titre_Pack): static
    {
        $this->titre_Pack = $titre_Pack;

        return $this;
    }

    public function getDescriptionPack(): ?string
    {
        return $this->description_Pack;
    }

    public function setDescriptionPack(string $description_Pack): static
    {
        $this->description_Pack = $description_Pack;

        return $this;
    }

    public function getPrixPack(): ?string
    {
        return $this->prix_Pack;
    }

    public function setPrixPack(string $prix_Pack): static
    {
        $this->prix_Pack = $prix_Pack;

        return $this;
    }

    public function getDatePack(): ?string
    {
        return $this->date_Pack;
    }

    public function setDatePack(string $date_Pack): static
    {
        $this->date_Pack = $date_Pack;

        return $this;
    }
}

src/Entity/Guide.php
<?php

namespace App\Entity;

use App\Repository\GuideRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GuideRepository::class)]
class Guide
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_guide = null;

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomGuide(): ?string
    {
        return $this->nom_guide;
    }

    public function setNomGuide(string $nom_guide): static
    {
        $this->nom_guide = $nom_guide;

        return $this;
    }
}

src/Entity/Pack.php
<?php

namespace App\Entity;

use App\Repository\PackRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PackRepository::class)]
class Pack
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: "Please enter a title.")]
    #[ORM\Column(length: 255)]
    private ?string $titrePack = null;

    #[Assert\NotBlank(message: "Please enter a description.")]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $descriptionPack = null;

    #[Assert\NotBlank(message: "Please enter a price.")]
    #[ORM\Column]
    private ?int $prixPack = null;

    #[ORM\Column(length: 255)]
    private ?string $imagePack = null;

    #[Assert\NotBlank(message: "Please select a departure date.")]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateDepartPack = null;

    #[Assert\NotBlank(message: "Please select an arrival date.")]
    #[Assert\GreaterThan(propertyPath: "dateDepartPack", message: "The arrival date must be after the departure date.")]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateArrivePack = null;

    #[ORM\OneToMany(targetEntity: ReservationPack::class, mappedBy: 'pack')]
    private Collection $reservations;

    #[ORM\OneToOne]
    private ?Transport $transports = null;

    #[ORM\OneToOne]
    private ?Guide $guide = null;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitrePack(): ?string
    {
        return $this->titrePack;
    }

    public function setTitrePack(string $titrePack): static
    {
        $this->titrePack = $titrePack;

        return $this;
    }

    public function getDescriptionPack(): ?string
    {
        return $this->descriptionPack;
    }

    public function setDescriptionPack(string $descriptionPack): static
    {
        $this->descriptionPack = $descriptionPack;

        return $this;
    }

    public function getPrixPack(): ?int
    {
        return $this->prixPack;
    }

    public function setPrixPack(int $prixPack): static
    {
        $this->prixPack = $prixPack;

        return $this;
    }

    public function getImagePack(): ?string
    {
        return $this->imagePack;
    }

    public function setImagePack(string $imagePack): static
    {
        $this->imagePack = $imagePack;

        return $this;
    }

    public function getDateDepartPack(): ?\DateTimeInterface
    {
        return $this->dateDepartPack;
    }

    public function setDateDepartPack(\DateTimeInterface $dateDepartPack): static
    {
        $this->dateDepartPack = $dateDepartPack;

        return $this;
    }

    public function getDateArrivePack(): ?\DateTimeInterface
    {
        return $this->dateArrivePack;
    }

    public function setDateArrivePack(\DateTimeInterface $dateArrivePack): static
    {
        $this->dateArrivePack = $dateArrivePack;

        return $this;
    }

    /**
     * @return Collection<int, ReservationPack>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(ReservationPack $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setPack($this);
        }

        return $this;
    }

    public function removeReservation(ReservationPack $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getPack() === $this) {
                $reservation->setPack(null);
            }
        }

        return $this;
    }

    public function getTransports(): ?Transport
    {
        return $this->transports;
    }

    public function setTransports(?Transport $transports): static
    {
        $this->transports = $transports;

        return $this;
    }

    public function getGuide(): ?Guide
    {
        return $this->guide;
    }

    public function setGuide(?Guide $guide): static
    {
        $this->guide = $guide;

        return $this;
    }
}

Ziyara/src/Form/PackType.php
<?php

namespace App\Form;

use App\Entity\Pack;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre_Pack')
            ->add('description_Pack')
            ->add('prix_Pack')
            ->add('date_Pack')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pack::class,
        ]);
    }
}

Ziyara/src/Controller/PackController.php
<?php

namespace App\Controller;

use App\Entity\Pack;
use App\Form\PackType;
use App\Repository\PackRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pack')]
class PackController extends AbstractController
{
    #[Route('/', name: 'app_pack_index', methods: ['GET'])]
    public function index(PackRepository $packRepository): Response
    {
        return $this->render('back/pack/index.html.twig', [
            'packs' => $packRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_pack_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $pack = new Pack();
        $form = $this->createForm(PackType::class, $pack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($pack);
            $entityManager->flush();

            return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/pack/new.html.twig', [
            'pack' => $pack,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pack_show', methods: ['GET'])]
    public function show(Pack $pack): Response
    {
        return $this->render('back/pack/show.html.twig', [
            'pack' => $pack,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pack_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Pack $pack, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PackType::class, $pack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/pack/edit.html.twig', [
            'pack' => $pack,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pack_delete', methods: ['POST'])]
    public function delete(Request $request, Pack $pack, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pack->getId(), $request->request->get('_token'))) {
            $entityManager->remove($pack);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/PackController.php
<?php

namespace App\Controller;

use App\Entity\Pack;
use App\Form\Pack1Type;
use App\Repository\PackRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/pack')]
class PackController extends AbstractController
{
    #[Route('/', name: 'app_pack_index', methods: ['GET'])]
    public function index(PackRepository $packRepository): Response
    {
        return $this->render('pack/index.html.twig', [
            'packs' => $packRepository->findAll(),
        ]);
    }

    #[Route('/front', name: 'app_packfront_index', methods: ['GET'])]
    public function indexfront(PackRepository $packRepository): Response
    {
        return $this->render('pack/indexFront.html.twig', [
            'packs' => $packRepository->findAll(),
        ]);
    }


    #[Route('/new', name: 'app_pack_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $pack = new Pack();
        $form = $this->createForm(Pack1Type::class, $pack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Check if the guide is already used by another pack
            $existingGuide = $entityManager->getRepository(Pack::class)->findOneBy(['guide' => $pack->getGuide()]);
            // Check if the transporter is already used by another pack
            $existingTransport = $entityManager->getRepository(Pack::class)->findOneBy(['transports' => $pack->getTransports()]);

            if ($existingGuide) {
                $this->addFlash('danger', 'Guide is already used by another pack.');
            }

            if ($existingTransport) {
                $this->addFlash('danger', 'Transporter is already used by another pack.');
            }

            if (!$existingGuide && !$existingTransport) {
                /** @var UploadedFile $imageFile */
                $imageFile = $form->get('imagePack')->getData();

                if ($imageFile) {
                    $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                    // Move the file to the directory where your images are stored
                    try {
                        $imageFile->move(
                            $this->getParameter('img_directory'), // specify the directory where images should be stored
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // Handle the exception if something happens during the file upload
                    }

                    // Update the 'image' property to store the file name instead of its contents
                    $pack->setImagePack($newFilename);
                }

                $entityManager->persist($pack);
                $entityManager->flush();

                $this->addFlash('success', 'Pack' . $pack->getTitrePack() . ' created successfully!');

                return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->renderForm('pack/new.html.twig', [
            'pack' => $pack,
            'form' => $form,
        ]);
    }

    // #[Route('/new', name: 'app_pack_new', methods: ['GET', 'POST'])]
    // public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    // {
    //     $pack = new Pack();
    //     $form = $this->createForm(Pack1Type::class, $pack);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         /** @var UploadedFile $imageFile */
    //         $imageFile = $form->get('imagePack')->getData();

    //         if ($imageFile) {
    //             $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
    //             $safeFilename = $slugger->slug($originalFilename);
    //             $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

    //             // Move the file to the directory where your images are stored
    //             try {
    //                 $imageFile->move(
    //                     $this->getParameter('img_directory'), // specify the directory where images should be stored
    //                     $newFilename
    //                 );
    //             } catch (FileException $e) {
    //                 // Handle the exception if something happens during the file upload
    //             }

    //             // Update the 'image' property to store the file name instead of its contents
    //             $pack->setImagePack($newFilename);
    //         }

    //         $entityManager->persist($pack);
    //         $entityManager->flush();

    //         return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->renderForm('pack/new.html.twig', [
    //         'pack' => $pack,
    //         'form' => $form,
    //     ]);
    // }


    #[Route('/{id}', name: 'app_pack_show', methods: ['GET'])]
    public function show(Pack $pack): Response
    {
        return $this->render('pack/show.html.twig', [
            'pack' => $pack,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pack_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Pack $pack, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Pack1Type::class, $pack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pack/edit.html.twig', [
            'pack' => $pack,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pack_delete', methods: ['POST'])]
    public function delete(Request $request, Pack $pack, EntityManagerInterface $entityManager): Response
    {
        $reservations = $pack->getReservations();

        // Check if there are any reservations associated with the pack
        if ($reservations->isEmpty()) {
            if ($this->isCsrfTokenValid('delete' . $pack->getId(), $request->request->get('_token'))) {
                $entityManager->remove($pack);
                $entityManager->flush();
            }
            $this->addFlash('success', 'The pack' . $pack->getTitrePack() . ' successfully Deleted! ');

            return $this->redirectToRoute('app_pack_index', [], Response::HTTP_SEE_OTHER);
        } else {
            // If there are reservations associated with the pack, handle accordingly
            $this->addFlash('danger', 'the pack' . $pack->getTitrePack() . ' is already reserved ');
            return $this->redirectToRoute('app_pack_index');
        }
    }
}

templates/pack/_form.html.twig
{{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}
<div class="form-row">
	<div class="form-group col-md-6">
		{{ form_label(form.titrePack) }}
		{{ form_widget(form.titrePack, {'attr': {'class': 'form-control', 'placeholder': 'Title'}}) }}
		{{ form_errors(form.titrePack) }}
		{# Display validation errors for title #}
	</div>
	<div class="form-group col-md-6">
		{{ form_label(form.descriptionPack) }}
		{{ form_widget(form.descriptionPack, {'attr': {'class': 'form-control', 'placeholder': 'Description'}}) }}
		{{ form_errors(form.descriptionPack) }}
		{# Display validation errors for description #}
	</div>
</div>
<div class="form-row">
	<div class="form-group col-md-6">
		{{ form_label(form.prixPack) }}
		{{ form_widget(form.prixPack, {'attr': {'class': 'form-control', 'placeholder': 'Price'}}) }}
		{{ form_errors(form.prixPack,{'attr':{'class':'text-danger'}}) }}
		{# Display validation errors for price #}
	</div>
	<div class="form-group col-md-6">
		{{ form_label(form.imagePack) }}
		{{ form_widget(form.imagePack, {'attr': {'class': 'form-control'}}) }}
		{{ form_errors(form.imagePack,{'attr':{'class':'text-danger'}}) }}
		{# Display validation errors for image #}
	</div>
</div>
<div class="form-row">
	<div class="form-group col-md-6">
		{{ form_label(form.dateDepartPack) }}
		{{ form_widget(form.dateDepartPack, {'attr': {'class': 'form-control', 'placeholder': 'Departure Date'}}) }}
		{{ form_errors(form.dateDepartPack,{'attr':{'class':'text-danger'}}) }}
		{# Display validation errors for departure date #}
	</div>
	<div class="form-group col-md-6">
		{{ form_label(form.dateArrivePack) }}
		{{ form_widget(form.dateArrivePack, {'attr': {'class': 'form-control', 'placeholder': 'Arrival Date'}}) }}
		{{ form_errors(form.dateArrivePack) }}
		{# Display validation errors for arrival date #}
	</div>
</div>

<div class="form-row">
	<div class="form-group col-md-6">
		{{ form_label(form.transports) }}
		{{ form_widget(form.transports, {'attr': {'class': 'form-control'}}) }}
		{{ form_errors(form.transports) }}
		{# Display validation errors for transports #}
	</div>
	<div class="form-group col-md-6">
		{{ form_label(form.guide) }}
		{{ form_widget(form.guide, {'attr': {'class': 'form-control'}}) }}
		{{ form_errors(form.guide) }}
		{# Display validation errors for guide #}
	</div>
</div>
<button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pack/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Edit Pack{% endblock %}

{% block body %}
    <h1>Edit Pack</h1>

    {{ include('pack/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_pack_index') }}">back to list</a>

    {{ include('pack/_delete_form.html.twig') }}
{% endblock %}

templates/pack/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Pack index
{% endblock %}

{% block body %}
	<h1>Pack index</h1>
	{% for message in app.flashes('danger') %}
		<div class="alert alert-danger">{{ message }}</div>
	{% endfor %}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success">{{ message }}</div>
	{% endfor %}

	<div class="row">
		{% for pack in packs %}
			<div class="col-md-4 mb-4">
				<div class="card">
					<img src="{{ asset('img/' ~ pack.imagePack) }}" class="card-img-top" alt="{{ pack.titrePack }}">
					<div class="card-body">
						<h5 class="card-title">{{ pack.titrePack }}</h5>
						<p class="card-text">Description :{{ pack.descriptionPack }}</p>
						<p class="card-text">Price:
							{{ pack.prixPack }}
							TND</p>
						<p class="card-text">Departure Date:
							{{ pack.dateDepartPack ? pack.dateDepartPack|date('Y-m-d') : '' }}</p>
						<p class="card-text">Arrival Date:
							{{ pack.dateArrivePack ? pack.dateArrivePack|date('Y-m-d') : '' }}</p>
						<a href="{{ path('app_pack_show', {'id': pack.id}) }}" class="btn btn-primary">Show</a>
						<a href="{{ path('app_pack_edit', {'id': pack.id}) }}" class="btn btn-secondary">Edit</a>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col">
				<p>No records found</p>
			</div>
		{% endfor %}
	</div>

	<a href="{{ path('app_pack_new') }}" class="btn btn-success">Create new</a>
{% endblock %}

templates/pack/indexFront.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pack index
{% endblock %}

{% block body %}
	<h1>Pack index</h1>

	<div class="row">
		{% for pack in packs %}
			<div class="col-md-4 mb-4">
				<div class="card">
					<img src="{{ asset('img/' ~ pack.imagePack) }}" class="card-img-top" alt="{{ pack.titrePack }}">
					<div class="card-body">
						<h5 class="card-title">{{ pack.titrePack }}</h5>
						<p class="card-text">Description :{{ pack.descriptionPack }}</p>
						<p class="card-text">Price:
							{{ pack.prixPack }}
							TND</p>
						<p class="card-text">Departure Date:
							{{ pack.dateDepartPack ? pack.dateDepartPack|date('Y-m-d') : '' }}</p>
						<p class="card-text">Arrival Date:
							{{ pack.dateArrivePack ? pack.dateArrivePack|date('Y-m-d') : '' }}</p>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col">
				<p>No records found</p>
			</div>
		{% endfor %}
	</div>

	<a href="{{ path('app_reservation_pack_new') }}" class="btn btn-success">Reserver</a>
{% endblock %}

templates/pack/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}New Pack
{% endblock %}

{% block body %}
	<h1>Create new Pack</h1>

	{% for message in app.flashes('success') %}
		<div class="alert alert-success">{{ message }}</div>
	{% endfor %}

	{% for message in app.flashes('danger') %}
		<div class="alert alert-danger">{{ message }}</div>
	{% endfor %}

	{{ include('pack/_form.html.twig') }}

	<a href="{{ path('app_pack_index') }}">Back to list</a>

</script>{% endblock %}

templates/pack/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}Pack
{% endblock %}

{% block body %}

	<div class="container">
		<div class="card">
			<img src="{{ asset('img/' ~ pack.imagePack) }}" class="card-img-top" alt="{{ pack.titrePack }}">
			<div class="card-body">
				<h5 class="card-title">{{ pack.titrePack }}</h5>
				<p class="card-text">{{ pack.descriptionPack }}</p>
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<strong>Id:</strong>
					{{ pack.id }}</li>
				<li class="list-group-item">
					<strong>Prix:</strong>
					{{ pack.prixPack }}</li>
				<li class="list-group-item">
					<strong>Date de départ:</strong>
					{{ pack.dateDepartPack ? pack.dateDepartPack|date('Y-m-d') : '' }}</li>
				<li class="list-group-item">
					<strong>Date d'arrivée:</strong>
					{{ pack.dateArrivePack ? pack.dateArrivePack|date('Y-m-d') : '' }}</li>
				<li class="list-group-item">
					<strong>Reservations:</strong>
					<ul>
						{% for reservation in pack.reservations %}
							<li>
								Date:
								{{ reservation.dateReservationPack ? reservation.dateReservationPack|date('Y-m-d') : '' }},
																                            Number of Participants:
								{{ reservation.nbrParticipantPack }},
																                            User:
								{{ reservation.user.email }}
							</li>
						{% endfor %}
					</ul>
				</li>
				<li class="list-group-item">
					<strong>Transport:</strong>
					{{ pack.transports ? pack.transports.prixTransport : 'N/A' }}</li>
				<li class="list-group-item">
					<strong>Guide:</strong>
					{{ pack.guide ? pack.guide.nomGuide : 'N/A' }}</li>
			</ul>
			<div class="card-body">
				<a href="{{ path('app_pack_index') }}" class="btn btn-secondary">Back to List</a>
				<a href="{{ path('app_pack_edit', {'id': pack.id}) }}" class="btn btn-primary">Edit</a>

				{{ include('pack/_delete_form.html.twig') }}
			</div>
		</div>
	</div>
{% endblock %}